# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_auto_20161004_2058'),
        ('therapist', '0002_auto_20161004_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Therapist',
        ),
    ]
