# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0004_entity_patient'),
        ('therapist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('puntaje', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('tiempo', models.IntegerField()),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Minigame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TherapySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('objetivo', models.CharField(max_length=128)),
                ('descripcion', models.CharField(max_length=1024)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapist.Therapist')),
            ],
        ),
        migrations.AddField(
            model_name='minigame',
            name='movimientos',
            field=models.ManyToManyField(to='start.Movement'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='minigame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.Minigame'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='terapia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.TherapySession'),
        ),
    ]
