# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='fecha',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='gamesession',
            old_name='nivel',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='gamesession',
            old_name='puntaje',
            new_name='repetitions',
        ),
        migrations.RenameField(
            model_name='gamesession',
            old_name='repeticiones',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='gamesession',
            old_name='terapia',
            new_name='therapy',
        ),
        migrations.RenameField(
            model_name='gamesession',
            old_name='tiempo',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='minigame',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='minigame',
            old_name='movimientos',
            new_name='movements',
        ),
        migrations.RenameField(
            model_name='minigame',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='movement',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='therapysession',
            old_name='fecha',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='therapysession',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='therapysession',
            old_name='objetivo',
            new_name='objective',
        ),
        migrations.RenameField(
            model_name='therapysession',
            old_name='paciente',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='therapysession',
            old_name='terapeuta',
            new_name='therapist',
        ),
    ]
