# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_auto_20161004_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='minigame',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='therapy',
        ),
        migrations.RemoveField(
            model_name='minigame',
            name='movements',
        ),
        migrations.RemoveField(
            model_name='therapysession',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='therapysession',
            name='therapist',
        ),
        migrations.DeleteModel(
            name='GameSession',
        ),
        migrations.DeleteModel(
            name='Minigame',
        ),
        migrations.DeleteModel(
            name='Movement',
        ),
        migrations.DeleteModel(
            name='TherapySession',
        ),
    ]
