# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('ocupacion', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('FIM_inicial', models.PositiveIntegerField()),
                ('FIM_final', models.PositiveIntegerField()),
            ],
        ),
    ]
