# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_entity_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='numero_documento',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
