# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0005_auto_20161004_2104'),
        ('patient', '0005_auto_20161004_0146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
