# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0006_auto_20161004_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('id_type', models.CharField(max_length=50)),
                ('id_num', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('entity', models.CharField(max_length=50)),
            ],
        ),
    ]
